Homeworks/Architecture MVC/Twitter/Web/Models/ViewModels/TweetViewModel.cs
using System.ComponentModel.DataAnnotations;
namespace Web.Models
{
    public class CreateTweetViewModel
    {
        [Required]
        [Display(Name = "Compose new Tweet")]
        [StringLength(140, ErrorMessage = "The Tweet can be up to {1} characters long.", MinimumLength = 1)]
        public string Content { get; set; }
    }

}

Homeworks/Architecture MVC/Twitter/Web/Controllers/TweetsController.cs
using System;
using System.Threading.Tasks;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Twitter.Data;
using Twitter.Data.Models;
using Web.Models;
using Web.Models.ViewModels;

namespace Web.Controllers
{
    public class TweetsController :BaseController
    {

        [Authorize]
        public ActionResult CreateTweet ()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult CreateTweet(CreateTweetViewModel model)
        {
            
            if (ModelState.IsValid)
            {
                var loggedUserId = User.Identity.GetUserId();

                var tweet = new Tweet
                {
                    CreatedAt = DateTime.Now,
                    Content = model.Content,
                    UserId = loggedUserId
                };

                this.Data.Tweets.Add(tweet);
                this.Data.SaveChanges();

                return RedirectToAction("Index", "Home");
            }
            return View(model);
        }
    }
}

Homeworks/Architecture MVC/Twitter/Web/Views/Tweets/CreateTweet.cshtml
@model Web.Models.CreateTweetViewModel
@{
    ViewBag.Title = "CreateTweet";
}
<h2>Compose new Tweet</h2>
@using (Html.BeginForm("CreateTweet", "Tweets", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary("", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(m => m.Content, "", new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextAreaFor(m => m.Content, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Tweet" />
        </div>
    </div>
}