Homeworks/Web Security/Twitter.Web/Controllers/NotificationsController.cs
namespace Twitter.Web.Controllers
{
    using System;
    using System.Linq;
    using System.Web.Mvc;
    using Models.ViewModels;
    using Twitter.Models;

    public class NotificationsController : BaseController
    {
        [HttpPost]
        [Authorize]
        public ActionResult AddNotification(string userId, string message)
        {
            var targetUser = this.Data.Users.Find(userId);

            if (targetUser == null)
            {
                return this.HttpNotFound();
            }

            var notification = new Notification
            {
                Message = message,
                IsRead = false,
                Date = DateTime.Now
            };

            targetUser.Notifications.Add(notification);
            this.Data.SaveChanges();


            return this.Content("true");
        }

        [HttpGet]
        [Authorize]
        public ActionResult Index()
        {
            var notifications = this.Data.Notifications.All()
                .Where(n => n.User.UserName == this.User.Identity.Name)
                .OrderByDescending(n => n.Date);

            foreach (var notification in notifications)
            {
                notification.IsRead = true;
            }

            this.Data.SaveChanges();
            this.ViewBag.notifications = 0;

            return this.View(notifications.Select(NotificationViewModel.Create).AsEnumerable());
        }
    }
}

Homeworks/Web Security/Twitter.Web/Controllers/UsersController.cs
namespace Twitter.Web.Controllers
{
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using System.Web;
    using System.Web.Mvc;
    using Infrastructure;
    using Microsoft.AspNet.Identity;
    using Microsoft.AspNet.Identity.Owin;
    using Models.BindingModels;
    using Models.ViewModels;
    using Twitter.Models;

    public class UsersController : BaseController
    {
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;

        public UsersController()
        {
        }

        public UsersController(ApplicationUserManager userManager, ApplicationSignInManager signInManager)
        {
            UserManager = userManager;
            SignInManager = signInManager;
        }

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set 
            { 
                _signInManager = value; 
            }
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        [HttpGet]
        public ActionResult Index(string username, int pageNum = 0)
        {
            var user = this.Data.Users.All()
                .Where(u => u.UserName == username)
                .Select(UserFullViewModel.Create)
                .FirstOrDefault();

            if (user == null)
            {
                return this.RedirectToAction("Index", "Home");
            }

            var tweets = this.GetRecordsForPage(user.Id, pageNum);

            if (this.Request.IsAjaxRequest())
            {
                return this.PartialView("DisplayTemplates/TweetViewModel", tweets);
            }

            var result = new UserWallViewModel
            {
                User = user, 
                Tweets = tweets
            };

            return View(result);
        }

        [HttpGet]
        [Authorize]
        public ActionResult Edit()
        {
            var username = this.User.Identity.Name;
            var userData = this.Data.Users.All()
                .Where(u => u.UserName == username)
                .Select(EditProfileViewModel.Create)
                .FirstOrDefault();

            return View(userData);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(EditProfileBindingModel model)
        {
            if (this.ModelState.IsValid)
            {
                var user = await this.UserManager.FindByIdAsync(this.User.Identity.GetUserId());
                user.Fullname = model.Fullname;
                user.Email = model.Email;

                var result = await this.UserManager.UpdateAsync(user);

                if (result.Succeeded)
                {
                    await this.SignInManager.SignInAsync(user, isPersistent: false, rememberBrowser: false);

                    this.TempData["Success"] = new[] {"Edit successfull"};
                }
                else
                {
                    this.AddErrors(result);
                }
            }

            return View(model);
        }

        [HttpGet]
        [Authorize]
        public ActionResult Users()
        {
            var users = this.Data.Users.All()
                    .Where(u => u.UserName != this.User.Identity.Name)
                    .Select(UserPreviewViewModel.Create)
                    .AsEnumerable();

            return this.View(users);
        }

        [HttpPost]
        [Authorize]
        public ActionResult FollowUser(string userId)
        {
            var targetUser = this.Data.Users.Find(userId);
            if (targetUser == null || targetUser.Followers.Any(u => u.UserName == this.User.Identity.Name))
            {
                return this.HttpNotFound();
            }

            targetUser.Followers.Add(this.UserProfile);
            this.UserProfile.FollowingUsers.Add(targetUser);

            this.Data.SaveChanges();

            return this.Content(this.UserProfile.Fullname + " followed you.");
        }

        [HttpPost]
        [Authorize]
        public ActionResult UnfollowUser(string userId)
        {
            var targetUser = this.Data.Users.Find(userId);
            if (targetUser == null || targetUser.Followers.All(u => u.UserName != this.User.Identity.Name))
            {
                return this.HttpNotFound();
            }

            targetUser.Followers.Remove(this.UserProfile);
            this.UserProfile.FollowingUsers.Remove(targetUser);

            this.Data.SaveChanges();

            return this.Content("");
        }

        private IEnumerable<TweetViewModel> GetRecordsForPage(string userId, int pageNum)
        {
            IQueryable<Tweet> tweets =
                this.Data.Tweets.All()
                .Where(t => t.AuthorId == userId)
                .OrderByDescending(t => t.PostedOn);

            var result = tweets
                    .Skip(AppConfig.TweetsPerPage * pageNum)
                    .Take(AppConfig.TweetsPerPage)
                    .Select(TweetViewModel.Create)
                    .AsEnumerable();

            return result;
        }

        private void AddErrors(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error);
            }
        }
    }
}

Homeworks/Web Security/Twitter.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="wpageth=device-wpageth, initial-scale=1.0">
    <title>@ViewBag.Title - Twitter</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Twitter", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home", routeValues: null, htmlAttributes: null)</li>
                    @Html.Partial("_NavBarLinks")
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Twitter Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/signalr")
    <script src="/signalr/hubs"></script>
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <script>
        $(document).ready(function() {
            var notificationsHub = $.connection.notifications;
            notificationsHub.client.receiveNotification = function () {
                console.log(1);
                $('#notifications').html(parseInt($('#notifications').html(), 10) + 1);
            };
            $.connection.hub.start();
            
        });
    </script>
</body>
</html>

Homeworks/Web Security/Twitter.Web/Views/Shared/_Messages.cshtml
@using System.Collections
@model TempDataDictionary

@if (Model["success"] != null)
{
    <div class="alert alert-success fade in">
        <span class="close" data-dismiss="alert">&times;</span>
        <strong>Success!</strong>

        @foreach (var message in @Model["success"] as IEnumerable)
        {
            <p>@message</p>
        }
    </div>
}

@if (Model["error"] != null)
{
    <div class="alert alert-danger fade in">
        <span class="close" data-dismiss="alert">&times;</span>
        <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
        <span class="sr-only">Error:</span>
        <strong>Error!</strong> 
        @foreach (var message in @Model["error"] as IEnumerable)
        {
            <p>@message</p>
        }
    </div>
}

Homeworks/Web Security/Twitter.Web/Views/Shared/_NavbarLinks.cshtml
@if (Request.IsAuthenticated)
{
    <li>@Html.ActionLink(User.Identity.Name, "Index", "Users", routeValues: new {username = User.Identity.Name}, htmlAttributes: null)</li>
    <li>@Html.ActionLink("Users", "Users", "Users", routeValues: null, htmlAttributes: null)</li>
    <li>@*@Html.ActionLink("Noitications <span class=\"badget\">0</span>", "UserNotifications", "Notifications", routeValues: null, htmlAttributes: null)*@</li>
    <li>
        <a href="@Url.Action("Index", "Notifications", null)">
            <span>Notifications</span>
            <span id="notifications" class="badge"> @ViewBag.notifications</span>
        </a>
    </li>
}
